### ISSUE TITLE
Something is funky

### ISSUE THREAD

**Issue by WhatsTheIssue** [AHigi/TidyPlates#1]
I have tracked this down to TidyPlates (it occurs on Beta+Live).

The only addons running when this occurs is:
Tidy Plates
+ Hub
+ Widgets
+ Grey Theme

When playing in windowed mode (not borderless, proper windowed mode), if maximising from a smaller window or just resizing in general, the entire client will freeze for 5-10 seconds. (**Not minimising/maximising**)

I can't seem to get any LUA error to pop so I assume there's some mega-processing happening by the addon.

Tried DX11/DX12 incase it was some sort of rendering issue.

It is not based on the amount of 'plates around, went to a dead area of Mulgore on beta, 2-3 units in range and it still occurs.

**Comment by WhatsTheIssue** [comment]
Very interesting, the option "Always Show Nameplates" (I shall refer to this as ASN) fixes whether this occurs.

Start WoW - ASN on **or** off - Issue occurs
Start WoW - Flip ASN value - Issue goes away
Start WoW - Flip ASN value - /reload - Issue occurs
Start WoW - Flip ASN value - /reload - Flip ASN value - Issue goes away

Maybe this helps?

**Comment by AHigi** [comment]
Thank you for noticing this and the very detailed report, I'm going to look into this...
Noticed it myself, but didn't give it much thought yet... Thought it was a blizz thing :P 
Anyways, this I'm gonna track this one down

**Comment by AHigi** [comment]
I was investigating this one today... I'm sure this has to do something with the widgets... but I wasn't able to find the solution yet

**Comment by WhatsTheIssue** [comment]
Thank you for the ongoing investigation. I am pretty sure it's a widget as well but no idea how to track it down.

**Comment by AHigi** [comment]
Yeah... I tried to systematically disable features of the widgets. But i think it is the widget framework that itself is causing this issue... Still, I haven't given up on this

**Comment by WhatsTheIssue** [comment]
I'm still convinced it's a null somewhere or similar. Otherwise there would be no reason toggling "Always Show Nameplates" on/off would fix it.

**Comment by guoqiyun** [comment]
It seems to be [fixed in the other project](https://github.com/Luxocracy/TidyPlates_BFA/commit/91d442333782930b1e576ab8b36144370178f575).

**Comment by ja0b** [comment]
Hey guys, kinda pointless to have 2 projects open for this, I wasn't aware of this other project, I actually was checking this issue right now.

@AHigi Could you get in touch with the other repo owner to merge this into one?

**Comment by WhatsTheIssue** [comment]
This has been confirmed as fixed, albeit in a different repo.

Hopefully AHigi and Lux can work together.

**Comment by AHigi** [comment]
If you want

**Comment by WhatsTheIssue** [comment]
Thank you @AHigi for fixing everything properly, the other fix had issues so he had to revert :)

**Comment by AHigi** [comment]
https://github.com/Luxocracy/TidyPlates_BFA
You can find my fixes there from now on :)

**Comment by ja0b** [comment]
Awesome guys! let's maintain this :)
